# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lagou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('jobkwd', models.CharField(blank=True, max_length=500, null=True)),
                ('salary', models.CharField(blank=True, max_length=500, null=True)),
                ('background', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.CharField(blank=True, max_length=500, null=True)),
                ('industry', models.CharField(blank=True, max_length=500, null=True)),
                ('companyurl', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('pages', models.IntegerField(unique=True)),
                ('classf', models.CharField(blank=True, max_length=500, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Lagou',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Newpages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newp', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'Newpages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Xiciproxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Xiciproxy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='svgdatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.TextField()),
            ],
        ),
    ]
